[tool.black]
line-length=79
skip-string-normalization=1
exclude=["*/migrations/", "venv/", "env/"]
[tool.isort] 
default_section = "THIRDPARTY" 
known_django = "django" 
sections = ["FUTURE","STDLIB","THIRDPARTY","DJANGO","FIRSTPARTY","LOCALFOLDER"] 
skip = [".gitignore", "venv/", "env/"] 
skip_glob = ["*/migrations/*"] 
multi_line_output = 3 
line_length = 79